import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import dotenv from "dotenv";
import path from "path";
import fs from "fs/promises";

// Load environment variables from .env file
dotenv.config();

// Build output directory (defaults to current directory when OUTPUT_PATH is not set)
const outputDir = path.resolve(process.env.OUTPUT_PATH ?? process.cwd());
const outFilePath = path.join(outputDir, "main.js");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

async function copyReleaseAssets() {
	const assets = ["manifest.json", "styles.css"];
	await fs.mkdir(outputDir, { recursive: true });

	for (const asset of assets) {
		const sourcePath = path.resolve(process.cwd(), asset);
		const destinationPath = path.resolve(outputDir, asset);
		if (sourcePath === destinationPath) continue;
		await fs.copyFile(sourcePath, destinationPath);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: outFilePath,
});

if (prod) {
	await context.rebuild();
	await copyReleaseAssets();
	console.log(`Build assets written to: ${outputDir}`);
	process.exit(0);
} else {
	await context.watch();
}
